TicketOffice\Sale\Entity\Customer:
    type: entity
    table: customer
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        email:
          type: string