# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ticket_office.sale.entity.ticket_repository:
        class: AppBundle\Entity\DoctrineTicketRepository
        arguments: ["@doctrine.orm.default_entity_manager"]

    ticket_office.sale.seat_picker:
      class: TicketOffice\Sale\Service\SeatPicker

    ticket_office.sale.pnr_generator:
      class: TicketOffice\Sale\Service\PNRGenerator

    ticket_office.commands.buy_ticket_handler:
        class: TicketOffice\Sale\Command\BuyTicketHandler
        arguments:
          - "@ticket_office.sale.seat_picker"
          - "@ticket_office.sale.pnr_generator"
          - "@ticket_office.sale.entity.ticket_repository"
        tags:
          - { name: command_handler, handles: TicketOffice\Sale\Command\BuyTicket }

    ticket_office.sale.entity.customer_repository:
        class: AppBundle\Entity\DoctrineCustomerRepository
        arguments: ["@doctrine.orm.default_entity_manager"]
